#!/usr/bin/python3
"""
Factorize numbers in a file into a product of two prime numbers
"""
import sys

def is_prime(number):
    if number <= 1:
        return False
    if number <= 3:
        return True
    if number % 2 == 0 or number % 3 == 0:
        return False
    i = 5
    while i * i <= number:
        if number % i == 0 or number % (i + 2) == 0:
            return False
        i += 6
    return True

def factorize():
    """
    A function to search file and factorize the given set of numbers into two prime numbers (format n = p*q)
    """
    try:
        file = sys.argv[1]
        with open(file) as f:
            for line_number in f:
                line_number = int(line_number)
                if line_number % 2 == 0:
                    print("{} = {} * {}".format(line_number, 2, line_number // 2))
                    continue
                
                for i in range(3, int(line_number**0.5) + 1, 2):
                    if line_number % i == 0 and is_prime(i) and is_prime(line_number // i):
                        print("{} = {} * {}".format(line_number, i, line_number // i))
                        break
                else:
                    print("{} = {} * {}".format(line_number, line_number, 1))
    except (IndexError, ValueError):
        pass

factorize()
